name: debts_manager
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get_it:
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider:
  path: ^1.8.0
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  pdf: ^3.6.1
  google_fonts:
  printing:
  esys_flutter_share:
  shared_preferences:

dev_dependencies:
  drift_dev: ^1.0.2
  build_runner:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/open-sans.ttf
    - assets/invoice.svg
    - assets/